---
kind: pipeline
name: default

steps:
- name: build
  image: rancher/dapper:1.11.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: build-all-binaries
  image: golang:1.19.7
  environment:
    CROSS: 1
    VERSION: ${DRONE_TAG}
  commands:
  - apt-get update
  - apt-get install -y xz-utils zip rsync jq curl ca-certificates
  - mkdir -p /go/src/github.com/rancher
  - ln -s /drone/src /go/src/github.com/rancher/terraform-provider-rke
  - cd /go/src/github.com/rancher/terraform-provider-rke
  - make build
  - make package
  when:
    event: tag

- name: gpg_sign_release
  image: plugins/gpgsign
  settings:
    key:
      from_secret: gpg_key
    passphrase:
      from_secret: gpg_passphrase
    files:
      - dist/artifacts/${DRONE_TAG}/terraform-provider-rke_*_SHA256SUMS
    detach_sign: true
    armor: false
  when:
    event: tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    prerelease: true
    files:
    - dist/artifacts/${DRONE_TAG}/terraform-provider-rke_*
    api_key:
      from_secret: github_token
  when:
    event: tag
    ref:
      include: [ refs/tags/*rc* ]

- name: github_binary_release
  image: plugins/github-release
  settings:
    files:
    - dist/artifacts/${DRONE_TAG}/terraform-provider-rke_*
    api_key:
      from_secret: github_token
  when:
    event: tag
    ref:
      exclude: [ refs/tags/*rc* ]

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
