language: go
go:
  - '1.12'
install:
  - make tools
script:
  - make test
before_deploy:
  - make build-x
deploy:
  provider: releases
  api_key:
    secure: uupNVCFnVNWOQdEtUUQZE3+gwe2yEX8/TewMyUBsN5k/8/hBlj2meD2fiSEplOVOZs//aptTKM+Hj3wzYxBUAoem3ayDsY1UUZlfqEBn9LWc9wFRgN3VdUPg147GbsxytMDBdIPDOH4NCLe5v7mvF7OSK/JnObglY1wz+9JQb9B/YWHHzucWmxWgJgFOKPXTNGiPy1/FAPwDPl7WdQVr6hyGJVEV8XU15ZzxLUPJWB8gdVI4wfohMSuCyCsu29iLiIuT4Xj6MqSfZZqrSMCXxShP7aGLxXV0j2ceFYHYJyn7D3VDPyhehCMOnagJcfqe1GGrxWgBLIZqYDRxUmm9Tm06CeS88y2RCRSSu+A89Xp5ErnVFAOPhtNwoIlNz0Iwe/OytkrF3P3sGOUsHGrEUekH7Se8+QnoVWHbutXKXi38PIDkr+Kxp285izo2258bRT8p/+QskyR9+kLVr8eHeX5COl8J6kzu/1rTAuHeEp4yAMhuvNA5PwiDJP0fplHTbfI1VMHNSKjcP2wmOPvEMN06BqZmOJxSQCgkU19D5SS3GStm9wS4dEmJ6HYoc8W1C0QrCk3n9oToFnrBAYJYdZBhWJK++hjXglXcaRZfg0+ScZT1hn105d8lUJA2EsPWoT5UxOSRUWezAFrBBpZNXSfmPWJWMkD+j2A3KNpQ0WQ=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  on:
    tags: true

