# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["github.com/yamamoto-febc/terraform-provider-rke/github.com/hashicorp/nomad*"]

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-getter"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  name = "github.com/rancher/rke"
  version = "0.1.9"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.5"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.5"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.5"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.5"

[[override]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "1.10.5"

[[override]]
  name = "github.com/docker/distribution"
  revision = "3800056b8832cf6075e78b282ac010131d8687bc"

[[override]]
  name = "github.com/docker/docker"
  revision = "ecf4125b85e0faa57d2739348e0d453c1d24d10c"

[[override]]
  name = "github.com/rancher/norman"
  revision = "c032c4611f2eec1652ef37d254f0e8ccf90c80aa"

[[override]]
  name = "github.com/rancher/types"
  revision = "42c4836915c23ee2da3918421ba0593879caad6c"

[[override]]
  name = "github.com/Microsoft/go-winio"
  revision = "ab35fc04b6365e8fcb18e6e9e41ea4a02b10b175"

[prune]
  go-tests = true
  unused-packages = true
